name: "adaptive-distributed-manager"

services:
    postgres:
        image: postgres:17
        container_name: addcp-postgres
        environment:
            POSTGRES_DB: addcp
            POSTGRES_USER: addcp
            POSTGRES_PASSWORD: addcp

        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
