spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/addcp
    username: addcp
    password: addcp

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

server:
  port: 8080